num_bases: 4
emb_dim: 100
num_layers: 7
dropout: 0.15
JK: none
lr: 0.001
l2: 0
num_epochs: 50
batch_size: 512
eval_batch_size: 256
num_workers: 4
seed: 1
data_path: None
offline_log: True
test_rep: 1
exp_name: ofa1
train_sample_size: -1
eval_sample_size: -1
rwpe: None
task_names: ['cora_link', 'cora_node', 'pubmed_link', 'pubmed_node', 'arxiv', 'WN18RR', 'FB15K237', 'wikics', 'chemblpre', 'chempcba', 'chemhiv']
llm_name: ST
llm_b_size: 1
val_interval: 1
d_multiple: [1.5, 2, 0.5, 2.5, 0.7, 0.6, 0.4, 2, 1, 2, 4]
d_min_ratio: [1, 1, 0.1, 2, 0.2, 0.1, 0.03, 1, 0.2, 0.2, 2]
exp_dir: ./saved_exp/2024-02-28 16:05:02.205562
log_project: full_cdm