node:
  cora:
    finetune_dataset: cora
    normalize: none
    finetune_epochs: 1000
    early_stop: 200
    batch_size: 0
    finetune_lr: 0.0005
    lambda_proto: 1
    lambda_proto_reg: 0
    lambda_act: 0.1
    trade_off: 0.1
    num_instances_per_class: 0
  pubmed:
    finetune_dataset: pubmed
    normalize: none
    finetune_epochs: 1000
    early_stop: 200
    batch_size: 0
    finetune_lr: 0.005
    lambda_proto: 0.1
    lambda_proto_reg: 0
    lambda_act: 1
    trade_off: 0.5
    num_instances_per_class: 0
  arxiv:
    finetune_dataset: arxiv
    normalize: none
    finetune_epochs: 1000
    early_stop: 200
    batch_size: 0
    finetune_lr: 0.0005
    lambda_proto: 1
    lambda_proto_reg: 0
    lambda_act: 0.1
    trade_off: 0.01
    num_instances_per_class: 0
  wikics:
    finetune_dataset: wikics
    normalize: none
    finetune_epochs: 2000
    early_stop: 500
    batch_size: 0
    finetune_lr: 0.0001
    lambda_proto: 1
    lambda_proto_reg: 0
    lambda_act: 1
    trade_off: 0.01
    num_instances_per_class: 0
link:
  WN18RR:
    finetune_dataset: WN18RR
    normalize: batch
    finetune_epochs: 1000
    early_stop: 200
    batch_size: 0
    finetune_lr: 0.001
    lambda_proto: 0.1
    lambda_proto_reg: 0
    lambda_act: 1
    trade_off: 0.7
    num_instances_per_class: 0
  FB15K237:
    finetune_dataset: FB15K237
    normalize: batch
    finetune_epochs: 3000
    early_stop: 200
    batch_size: 1024
    finetune_lr: 0.0005
    lambda_proto: 0.1
    lambda_proto_reg: 0
    lambda_act: 0.1
    trade_off: 0.9
    num_instances_per_class: 50
graph:
  chemhiv:
    finetune_dataset: chemhiv
    normalize: batch
    finetune_epochs: 100
    early_stop: 20
    batch_size: 1024
    finetune_lr: 0.0003
    lambda_proto: 0.1
    lambda_proto_reg: 0
    lambda_act: 1
    trade_off: 0.8
    num_instances_per_class: 1500
  chempcba:
    finetune_dataset: chempcba
    normalize: batch
    finetune_epochs: 50
    early_stop: 10
    batch_size: 1024
    finetune_lr: 0.001
    lambda_proto: 1
    lambda_proto_reg: 0
    lambda_act: 1
    trade_off: 0.5
    num_instances_per_class: 20
